version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

  nodeapp:
    # O serviço 'nodeapp' deve estar alinhado com 'mongodb'
    build: .
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo-data:
